set -g default-terminal "xterm-256color"
set -g terminal-overrides ",xterm-256color:Tc"
set -g focus-events on

set -s escape-time 0
set -g base-index 1
set -g display-time 700
set -g history-limit 10000
set -g mouse on

unbind C-b
set -g prefix C-t
bind C-f send-prefix
bind C-a send-prefix

unbind '"'
unbind %
bind '-' split-window -v -c "#{pane_current_path}"
bind '\' split-window -h -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"
bind -n S-left prev
bind -n S-right next

bind -n 'M-1' select-window -t 1
bind -n 'M-2' select-window -t 2
bind -n 'M-3' select-window -t 3
bind -n 'M-4' select-window -t 4
bind -n 'M-5' select-window -t 5
bind -n 'M-6' select-window -t 6
bind -n 'M-7' select-window -t 7
bind -n 'M-8' select-window -t 8
bind -n 'M-9' select-window -t 9

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

set -g set-titles on
set -g set-titles-string "#T"

set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

BG="#CCCCCC"
FG="#000000"
ALT="#C2C2C2"
DIM="#868686"
DARK="#000000"
SEL="#AEAEAE"

setw -g mode-style "fg=${BG} bg=${DARK}"

set -g pane-border-style "fg=${ALT}"
set -g pane-active-border-style "fg=${DARK}"

set -g status-style "bg=${BG},fg=${FG}"
set -g status-position bottom
set -g status-justify absolute-centre

wg_sep="#[fg=${DIM}] | "
wg_prfx="#[fg=${DARK},bold]#{?client_prefix,<PREFIX> ,}"
wg_time="#[fg=${FG}]%H:%M"
wg_date="#[fg=${FG}]%d/%b/%Y"

set -g status-left "#[fg=${DARK},bold][#S]"
set -g status-right "${wg_prfx}${wg_time}${wg_sep}${wg_date}"
set -g status-right-length 100
set -g status-left-length 100

set -g window-status-format "#[fg=${DIM}] #I:#W "
set -g window-status-current-format "#[fg=${DARK},bold,underscore] #I:#W "

set -g message-style "bg=${DARK} fg=${BG}"
